# <span style="color:blue"> Ada Tech</span>
# <span style="color:blue">Técnicas de Programação I - Python</span>

## <span style="color:blue">Numpy Parte II</span>
**Maurício Luiz Sobrinho**<br>
**Matheus Parreiras Andrade**<br>
**Ada**
---

## Numpy - Parte II
- Comparações
- Operações Avançadas: Reduções e Ordenação


---
## Numpy - Parte II

### Comparações
Comparações usando `==`, `>`,`<`,`>=`,`<=`, e `!=` também são feitas elemento por elemento.

In [22]:
A = np.arange(4).reshape(2,2)      # matriz 2x2
B = np.arange(6,2,-1).reshape(2,2) # matriz 2x2

M = (B == A)

print(A,'\n')
print(B,'\n')
print(M)

[[0 1]
 [2 3]] 

[[6 5]
 [4 3]] 

[[False False]
 [False  True]]


Para verificar se dois arrays são iguais (todos elementos são iguais) deve-se utilizar o método <font color='blue'>array_equal</font>.

In [16]:
A = np.arange(4).reshape(2,2)      # matrix 2x2
B = np.arange(6,2,-1).reshape(2,2) # matrix 2x2
C = np.copy(A)

# A resposta é apenas um valor booleano
print(np.array_equal(A,B))
print(np.array_equal(A,C))

# np.array_equal(A,B) é equivalente a:
D = (A==B)
print(np.all(D))

False
True
False


### Reduções
O <font color='blue'>numpy</font> possui métodos de redução como  <font color='blue'>sum</font>, <font color='blue'>max</font>, <font color='blue'>min</font>, <font color='blue'>argmax</font> e <font color='blue'>argmin</font>. Tais métodos podem ser aplicados ao array como um todo ou somente às linhas ou colunas.
O que controla a forma de aplicação é o parâmetro 'axis'. Quando o parâmetro 'axis' não é especificado, a redução é aplicada ao array todo. 
- 'axis' não especificado: retorna um valor único
- 'axis=0' restringe a redução às colunas (percorre as linhas): retorna um array com número de elementos igual ao número de colunas
- 'axis=1' restringe a redução às linhas (percorre as colunas): retorna um array com número de elementos igual ao número de linhas

In [26]:
A = np.zeros((5,5))  # matriz 5x5 de zeros
A[:] = np.arange(5)  # broadcasting o array [0,1,2,3,4] nas linhas

print(A,'\n')

print('Soma de todos os valores: ', np.sum(A)) # todos os elementos
print('Soma dos valores das colunas: ', np.sum(A,axis=0)) # soma os valores das colunas
print('Soma dos valores das linnhas: ', np.sum(A,axis=1)) # soma os valores das linhas

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]] 

Soma de todos os valores:  50.0
Soma dos valores das colunas:  [ 0.  5. 10. 15. 20.]
Soma dos valores das linnhas:  [10. 10. 10. 10. 10.]


In [19]:
A = np.random.randint(low=0,high=30,size=(5,5)) # matriz 5x5 com números inteiros 
                                                # randomicos no intervalor entre 0 e 30
print(A,'\n')

# todos os elementos
print('Maior valor dentre todos na matriz: ',np.max(A))    # maior valor da matriz
print('Posição do maior valor dentre todos na matriz: ',np.argmax(A)) # lineariza a matriz com A.ravel() e 
                                                                      # retorna a posicão do maior valor

# Por coluna
print('Maior valor em cada coluna: ',np.max(A,axis=0))  # maior valor em cada coluna
print('Posição do maior valor em cada coluna: ',np.argmax(A,axis=0)) # posição do maior valor em cada coluna

[[19  8 21  1 26]
 [12 15 15  2 20]
 [ 8  4 21 22  6]
 [17 14  4 20  5]
 [14  2 29  7 26]] 

Maior valor dentre todos na matriz:  29
Posição do maior valor dentre todos na matriz:  22
Maior valor em cada coluna:  [19 15 29 22 26]
Posição do maior valor em cada coluna:  [0 1 4 2 0]


Reduções estatísticas como:
- <font color='blue'>mean</font>: média aritmética
- <font color='blue'>median</font>: mediana 
- <font color='blue'>std</font>: desvio padrão

funcionam da mesma forma, ou seja, podem ser aplicados ao array como um todo ou somente às linhas e colunas utilizando o parâmetro 'axis'.

In [33]:
A = np.random.randint(low=0,high=30,size=(5,5)).astype(float)
print(A,'\n')

print('Media de todos os valores: ',np.mean(A))   # média de todos os valores
print('Media por coluna: ',np.mean(A,axis=0))     # média por coluna
print('Media por linha: ',np.mean(A,axis=1))      # média por linha

[[ 3.  9. 15. 21.  8.]
 [ 8. 20. 26. 27. 29.]
 [21. 28. 12. 29.  2.]
 [25. 13. 22.  9. 10.]
 [13. 29. 20. 14.  5.]] 

Media de todos os valores:  16.72
Media por coluna:  [14.  19.8 19.  20.  10.8]
Media por linha:  [11.2 22.  18.4 15.8 16.2]


#### Redução lógica
O métodos 
- <font color='blue'>all</font>: verifica se todos os elementos do array satisfazem a condição (True)
- <font color='blue'>any</font>: verifica se algum elemento do array satisfaz a condição (True)

também podem ser aplicados ao array como um todo ou somente às linhas e colunas utilizando o parâmetro 'axis'.

In [40]:
A = np.arange(25).reshape(5,5)
print(A,'\n')

M = A > 0
print(M,'\n')

print('Todos os elementos são TRUE? ', np.all(M))
print('Algum elemento é TRUE? ',np.any(M))

print('Todos os elementos de cada coluna são TRUE? ',np.all(M,axis=0))
print('Algum elemento de cada linha é TRUE? ',np.any(M,axis=1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[False  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]] 

Todos os elementos são TRUE?  False
Algum elemento é TRUE?  True
Todos os elementos de cada coluna são TRUE?  [False  True  True  True  True]
Algum elemento de cada linha é TRUE?  [ True  True  True  True  True]


### Ordenação 
#### <font color='blue'>sort</font>
O método <font color='blue'>sort</font> do <font color='blue'>numpy</font> ordena os elementos do array. 
- Quando o método <font color='blue'>sort</font> é invocado utilizando a própria variável, a ordenação é feita diretamente no array (inplace). Por exemplo:
```python
A = np.random.randint(low=0,high=30,size=(5,5))
A.sort()  # modifica o array original
```
- Quando o método <font color='blue'>sort</font> é invocado pelo <font color='blue'>numpy</font> uma cópia ordenada do array é gerada (o array original não é modificado).
```python
A = np.random.randint(low=0,high=30,size=(5,5))
B = np.sort(A)  # `B` é uma cópia de `A` com linhas ordenas (`A` não é afetado)
```

Por padrão a ordenação é feita em cada linha (`axis=1` é o valor padrão do parâmetro 'axis' no comando <font color='blue'>sort</font>) 

In [20]:
A = np.random.randint(low=0,high=30,size=(5,5))
print('Array original "A": \n',A,'\n')

B = np.sort(A) # `B` é uma cópia de `A` com linhas ordenas
print('"B" é cópia de "A" com valores das linhas ordenados. Array "A" não é alterado:')
print('B = \n',B,'\n')
print('A = \n',A,'\n')

Array original "A": 
 [[22  5 29 27  1]
 [21  8  1 17 26]
 [21  3  4  1 22]
 [19 19 24  4 18]
 [19  3  5 24 19]] 

"B" é cópia de "A" com valores das linhas ordenados. Array "A" não é alterado:
B = 
 [[ 1  5 22 27 29]
 [ 1  8 17 21 26]
 [ 1  3  4 21 22]
 [ 4 18 19 19 24]
 [ 3  5 19 19 24]] 

A = 
 [[22  5 29 27  1]
 [21  8  1 17 26]
 [21  3  4  1 22]
 [19 19 24  4 18]
 [19  3  5 24 19]] 



In [21]:
A.sort()  # as linhas de `A` são ordenadas modificando o array original
print('Os valores das linhas do array "A" são ordenados: \n A =\n',A,'\n')

A.sort(axis=0) # as COLUNAS de `A` são ordenadas modificando o array original
print('Os valores das colunas são ordenadas:  \n A =\n',A,'\n')

Os valores das linhas do array "A" são ordenados: 
 A =
 [[ 1  5 22 27 29]
 [ 1  8 17 21 26]
 [ 1  3  4 21 22]
 [ 4 18 19 19 24]
 [ 3  5 19 19 24]] 

Os valores das colunas são ordenadas:  
 A =
 [[ 1  3  4 19 22]
 [ 1  5 17 19 24]
 [ 1  5 19 21 24]
 [ 3  8 19 21 26]
 [ 4 18 22 27 29]] 



#### <font color='blue'>argsort</font>
O método <font color='blue'>argsort</font> retorna um array contendo os índicies dos elementos ordenados nas linhas. O parâmetro 'axis=0' pode ser utilizado para que a ordenação seja aplicada às colunas.   

In [60]:
A = np.array([[12.0,  1.0, 26.0],
              [23.0,  0.0,  7.0],
              [10.0,  19.0, 21.0]])
print(A,'\n')

I = np.argsort(A)  # fornece os indices dos elementos ordenados em cada linha
print(I,'\n')

for i in range(A.shape[0]):
    print('Indices dos elementos ordenados na linha ',i,': ',I[i])
    print('Linha',i,': '+10*' ',A[i])
    print('Linha ',i,' ordenada: ',A[i,I[i]],'\n')

[[12.  1. 26.]
 [23.  0.  7.]
 [10. 19. 21.]] 

[[1 0 2]
 [1 2 0]
 [0 1 2]] 

Indices dos elementos ordenados na linha  0 :  [1 0 2]
Linha 0 :            [12.  1. 26.]
Linha  0  ordenada:  [ 1. 12. 26.] 

Indices dos elementos ordenados na linha  1 :  [1 2 0]
Linha 1 :            [23.  0.  7.]
Linha  1  ordenada:  [ 0.  7. 23.] 

Indices dos elementos ordenados na linha  2 :  [0 1 2]
Linha 2 :            [10. 19. 21.]
Linha  2  ordenada:  [10. 19. 21.] 

